//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/InputsControle/EntradaControle.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @EntradaControle : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @EntradaControle()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""EntradaControle"",
    ""maps"": [
        {
            ""name"": ""Jogador"",
            ""id"": ""306fa20c-4c07-4ae3-8b1e-fbdd5b1cdd22"",
            ""actions"": [
                {
                    ""name"": ""Mover"",
                    ""type"": ""Value"",
                    ""id"": ""04996b28-28a1-4d26-95fa-59e0b3ba1983"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""GirarCamera"",
                    ""type"": ""Value"",
                    ""id"": ""a49f165a-d18d-4232-ae6a-b051353ead7e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""281508c9-fdac-4881-9eb0-1d53965bf0f4"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mover"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a922bd9c-1254-4cf8-91a9-f58a4718a4f4"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GirarCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Jogador
        m_Jogador = asset.FindActionMap("Jogador", throwIfNotFound: true);
        m_Jogador_Mover = m_Jogador.FindAction("Mover", throwIfNotFound: true);
        m_Jogador_GirarCamera = m_Jogador.FindAction("GirarCamera", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Jogador
    private readonly InputActionMap m_Jogador;
    private IJogadorActions m_JogadorActionsCallbackInterface;
    private readonly InputAction m_Jogador_Mover;
    private readonly InputAction m_Jogador_GirarCamera;
    public struct JogadorActions
    {
        private @EntradaControle m_Wrapper;
        public JogadorActions(@EntradaControle wrapper) { m_Wrapper = wrapper; }
        public InputAction @Mover => m_Wrapper.m_Jogador_Mover;
        public InputAction @GirarCamera => m_Wrapper.m_Jogador_GirarCamera;
        public InputActionMap Get() { return m_Wrapper.m_Jogador; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(JogadorActions set) { return set.Get(); }
        public void SetCallbacks(IJogadorActions instance)
        {
            if (m_Wrapper.m_JogadorActionsCallbackInterface != null)
            {
                @Mover.started -= m_Wrapper.m_JogadorActionsCallbackInterface.OnMover;
                @Mover.performed -= m_Wrapper.m_JogadorActionsCallbackInterface.OnMover;
                @Mover.canceled -= m_Wrapper.m_JogadorActionsCallbackInterface.OnMover;
                @GirarCamera.started -= m_Wrapper.m_JogadorActionsCallbackInterface.OnGirarCamera;
                @GirarCamera.performed -= m_Wrapper.m_JogadorActionsCallbackInterface.OnGirarCamera;
                @GirarCamera.canceled -= m_Wrapper.m_JogadorActionsCallbackInterface.OnGirarCamera;
            }
            m_Wrapper.m_JogadorActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Mover.started += instance.OnMover;
                @Mover.performed += instance.OnMover;
                @Mover.canceled += instance.OnMover;
                @GirarCamera.started += instance.OnGirarCamera;
                @GirarCamera.performed += instance.OnGirarCamera;
                @GirarCamera.canceled += instance.OnGirarCamera;
            }
        }
    }
    public JogadorActions @Jogador => new JogadorActions(this);
    public interface IJogadorActions
    {
        void OnMover(InputAction.CallbackContext context);
        void OnGirarCamera(InputAction.CallbackContext context);
    }
}
